tasks:
  redis:
    url: redis://my-redis.orb.local:6379
    enable-worker: true
  configs:
    - consumer-bean-name: org.example.SumTaskHandler#0
      task-name: org.example.SumTaskHandler#0
      data-type: org.example.SumTask
      running-timeout: 10000
      retry-times: 3
      worker-num: 10
      type: REDIS
    - consumer-bean-name: org.example.Sum2TaskHandler#0
      task-name: org.example.Sum2TaskHandler#0
      data-type: org.example.SumTask2
      running-timeout: 15000
      retry-times: 3
      worker-num: 10
      type: LOCAL